spring:
  application:
    name: sample-api

server:
  port: 8888
  tomcat:
    threads:
      max: 100          # 최대 스레드 수
      min-spare: 10     # 최소 유지 스레드 수
    max-connections: 8192   # 최대 동시 연결 수
    accept-count: 100       # 대기 큐 크기
    connection-timeout: 20000   # 연결 타임아웃 (ms)

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html